services:
  backend:
    build: ./src/backend
    container_name: billing_backend
    restart: always
    env_file:
      - ./src/backend/.env
    environment:
      - PORT=5000
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      - billing_net

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: billing_frontend
    restart: always
    ports:
      - "8080:80" # Host Port 8080 -> Container Port 80
    depends_on:
      - backend
    networks:
      - billing_net

networks:
  billing_net:
    driver: bridge
